In [2]:
#Source: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [3]:
import torch
torch.__version__

'1.7.1+cpu'

In [3]:
# Scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
# Vector
list_vector=[7,7]
vector = torch.tensor(list_vector)

In [8]:
vector.ndim

1

In [10]:
vector.shape #The above returns torch.Size([2]) which means our vector has a shape of [2]. This is because of the two elements we placed inside the square brackets ([7, 7]).


torch.Size([2])

In [12]:
# Matrix
matrix_vector=[[7,8],[9,10]]
matrix=torch.tensor(matrix_vector)

In [13]:
matrix.ndim #did you count the number of square brakcets on the outside of one side?

2

In [16]:
matrix.shape

torch.Size([2, 2])

In [19]:
# Tensor
tensor_matrix=[[[1,2,3],[3,6,9],[2,4,5]]]
tensor = torch.tensor(tensor_matrix)

In [20]:
tensor.ndim

3

In [22]:
tensor.shape #That means there's 1 dimension of 3 by 3.

torch.Size([1, 3, 3])

In [40]:
# random tensor
random_tensor=torch.rand(size=(1,2,5)) 
random_tensor

# Observations
# Last digit controls number of base instances
# Second last defines the number of observations of these instances
# Third one controls the total number of experiments (n=?)


tensor([[[0.6530, 0.3743, 0.6537, 0.9022, 0.9164],
         [0.1267, 0.9933, 0.7206, 0.1837, 0.2683]]])

In [43]:
# Example - 3 observations of a coin toss
coin_toss=torch.rand(size=(3,1))
coin_toss

tensor([[0.6290],
        [0.7592],
        [0.2117]])

In [46]:
# Example - 10 observations of a coin toss
coin_toss=torch.rand(size=(10,1))
coin_toss


tensor([[0.3846],
        [0.4871],
        [0.2113],
        [0.0213],
        [0.8999],
        [0.6096],
        [0.2189],
        [0.9603],
        [0.2219],
        [0.0447]])

In [47]:
# Example - 10 observations of a coin toss - repeated by 5 students
coin_toss_five_students=torch.rand(size=(5,10,1))
coin_toss_five_students

tensor([[[0.5943],
         [0.0574],
         [0.7197],
         [0.6876],
         [0.5030],
         [0.4528],
         [0.2225],
         [0.1601],
         [0.3392],
         [0.7985]],

        [[0.5695],
         [0.7527],
         [0.3483],
         [0.7266],
         [0.4084],
         [0.4981],
         [0.7365],
         [0.9384],
         [0.4032],
         [0.7204]],

        [[0.4854],
         [0.5398],
         [0.7828],
         [0.6898],
         [0.6035],
         [0.5800],
         [0.5435],
         [0.4268],
         [0.9398],
         [0.9742]],

        [[0.6024],
         [0.7226],
         [0.2873],
         [0.2906],
         [0.6801],
         [0.9898],
         [0.5675],
         [0.1530],
         [0.5109],
         [0.7398]],

        [[0.3812],
         [0.4444],
         [0.3554],
         [0.1097],
         [0.4963],
         [0.2305],
         [0.6332],
         [0.5707],
         [0.5657],
         [0.3143]]])

In [48]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [49]:
zero_to_ten_depracated = torch.range(0,10)
zero_to_ten_depracated

C:\Users\rtbf73\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  """Entry point for launching an IPython kernel.


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [51]:
zero_to_ten= torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
ten_zeros = torch.zeros_like(zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [53]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations perfromed on the tensor are recorded 

In [54]:
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [55]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [56]:
# Create a tensor
some_tensor = torch.rand(3,4)

In [57]:
some_tensor

tensor([[0.9428, 0.4765, 0.7866, 0.1784],
        [0.4212, 0.3511, 0.7503, 0.0757],
        [0.8883, 0.1161, 0.8316, 0.8161]])

In [58]:
# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.9428, 0.4765, 0.7866, 0.1784],
        [0.4212, 0.3511, 0.7503, 0.0757],
        [0.8883, 0.1161, 0.8316, 0.8161]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [5]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [60]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [61]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [62]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [63]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [64]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [65]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [66]:
tensor*tensor

tensor([1, 4, 9])

In [67]:
torch.matmul(tensor, tensor)

tensor(14)

In [68]:
tensor @ tensor

tensor(14)

In [6]:
# Not recommended - doing this by hand
value = 0
for i in range(len(tensor)):
    value+=tensor[i]*tensor[i]
value

tensor(14)

In [7]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32) # This is from the right: 2x3x2 so (2,3,2) ro 3x2

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32) # This is also (2,3,2) or 3x2

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [8]:
# View tensor_A and tensor_B.T
print(tensor_A) # 2,3,2 -> 3x2
print(tensor_B.T) # from right - 3x2x2 so 2,2,3 -> 2x3

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [9]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [11]:
# can also do:
torch.mm(tensor_A, tensor_B.T) #mm is a cool notation!

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
# cool stuff @ http://matrixmultiplication.xyz/

# For [1,2,3] x [2,5,1].T => you basically take each ROW of the second matrix, and multiply with the coefficients of the first one


In [12]:
### For torch.nn.Linear()
### y = mx + c...
### .. can be written as...
### y = xM + c...
### ... which becomes ...
### y = x A.T + b
### .. for linear algebrans.

In [13]:
# y = xA.T + b
###
# x => input layer 
# A => weights matrix, randomized and adjusted by SGD
# b => bias


In [14]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2,
                         out_features=6)

x = tensor_A
output = linear(x)


In [16]:
print(f"input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput Shape: {output.shape}")

input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward>)

Output Shape: torch.Size([3, 6])


In [17]:
# creating a damn tensor!
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [18]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [20]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")
# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [21]:
tensor.dtype

torch.int64

In [22]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [25]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [30]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [32]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [33]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [34]:
x_stacked = torch.stack([x,x,x,x], dim=0)

In [35]:
x_stacked # dim zero is like stacking bottom to top (along y-axis)

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [36]:
x_stacked_d1 = torch.stack([x,x,x,x], dim=1)

In [37]:
x_stacked_d1 # dim 1 is like stacking left to right (so along x-axis)

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [38]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [45]:
## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0) # dim 1 is y axis, dim 0 is x axis
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [46]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3)) # 3 channels on a 224x224 image for eg...

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0 -> 3x224x224 -> 224 channels in a 3x224 image...

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [47]:
# note --- if you change the values in the view, it will change the values of the original.

In [48]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [49]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [50]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

In [51]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [52]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [53]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [54]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [55]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [56]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [57]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Exercises


In [58]:
# Source: https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb

In [59]:
#2. Create a random tensor with shape (7, 7).
random_tensor = torch.rand(7,7)
random_tensor

tensor([[0.8016, 0.3649, 0.6286, 0.9663, 0.7687, 0.4566, 0.5745],
        [0.9200, 0.3230, 0.8613, 0.0919, 0.3102, 0.9536, 0.6002],
        [0.0351, 0.6826, 0.3743, 0.5220, 0.1336, 0.9666, 0.9754],
        [0.8474, 0.8988, 0.1105, 0.4563, 0.9719, 0.3968, 0.1496],
        [0.4743, 0.9973, 0.4436, 0.9726, 0.5194, 0.5337, 0.7050],
        [0.3362, 0.7891, 0.1694, 0.1800, 0.7177, 0.6988, 0.5510],
        [0.2485, 0.8518, 0.0963, 0.1338, 0.2741, 0.6142, 0.8973]])

In [61]:
# 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
second_tensor = torch.rand(1,7)

In [65]:
mult_tensor = torch.mm(random_tensor,second_tensor.T) #(1x7) and (7x1)=1x1
mult_tensor

tensor([[2.2194],
        [1.7779],
        [1.7665],
        [1.7591],
        [2.1161],
        [1.6599],
        [1.4596]])

In [76]:
#4. Set the random seed to 0 and do 2 & 3 over again.
torch.manual_seed(seed=0) 
torch.random.manual_seed(seed=0)
A = torch.rand(7,7)
B = torch.rand(1,7)
print(torch.mm(A,B.T)) # Correct solution

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


In [77]:
# Gonna skip GPU stuff... 5 & 6 exercises ("6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:")

In [78]:
tensor = torch.tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]])

In [79]:
tensor

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

In [82]:
# 8. Find the maximum and minimum values of the output of 7.
tensor.max(), tensor.min()

(tensor(0.5617), tensor(0.3647))

In [85]:
# 9. Find the maximum and minimum index values of the output of 7.
tensor.argmax(), tensor.argmin()

(tensor(3), tensor(0))

In [86]:
'''Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.'''

"Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape."

In [87]:
torch.manual_seed(seed=0) 
torch.random.manual_seed(seed=7)
r = torch.rand(1,1,1,10)
r

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])